### ISSUE TITLE
"No more data to read" for some input level 4 (PACK+ROLZ) w/ 32m+ buffers

### ISSUE THREAD

**Issue by udickow** [flanglet/kanzi#21] opened 2024-11-10 21:56 UTC
kanzi-cpp commit 6b57226e8e2168e5d2c0dadda505fe5f747bc99a (2024-10-19) gives error

`No more data to read in the bitstream. Error code: 13`

when attempting to decompress a stream created by compressing specific test data with level 4 (or just -t PACK+ROLZ -e NONE) using a buffer size of at least 32m.  This combination of options works fine for test data from e.g. /dev/zero or /dev/urandom but not for my specific log file.  I discovered the bug using a 5+ GiB log file today but can still reproduce it using just the first 32 MiB of the file.  The attached file contains these 32 MiB compressed down to 744448 bytes with kanzi -c -b 64m -t PACK -e TPAQX (the most efficient packing of this kind of highly repetitive log, a factor 1.25 smaller than using level 9 defaults).  The attached test file decompresses fine:

```
$ kanzi -d < kanzi-l4_b32m_error13_no_more_data.log.knz|wc -c
33554432

$ kanzi -d < kanzi-l4_b32m_error13_no_more_data.log.knz|sha256sum
162ca6bcb213184289b6a5076fcc37b34fdeda60b7a87b4b6bca442e5ce59628  -

$ kanzi -d < kanzi-l4_b32m_error13_no_more_data.log.knz|(head -3;echo ...;tail -3);echo
8 7 11 4 3 6 10 2 9 12 5: Qf= 99.42, sd=  1.15, d4=  2.00, Qc= 99.29, s=0.085, Qo= 90.24, P=12, S=900, N=66, Qf1av= 97.22, Qf1max= 98.17
8 3 11 4 7 6 10 2 9 12 5: Qf= 99.42, sd=  1.15, d4=  2.00, Qc= 99.29, s=0.085, Qo= 90.24, P=12, S=900, N=66, Qf1av= 97.19, Qf1max= 97.94
8 3 7 4 11 9 10 2 6 12 5: Qf= 99.42, sd=  1.15, d4=  2.00, Qc= 99.29, s=0.085, Qo= 90.24, P=12, S=900, N=66, Qf1av= 97.17, Qf1max= 97.82
...
8 3 7 6 12 9 11 4 2 5 10: Qf= 98.65, sd=  1.67, d4=  2.31, Qc= 98.53, s=0.122, Qo= 90.24, P=12, S=900, N=66, Qf1av= 96.20, Qf1max= 97.47
8 3 7 6 12 4 2 11 10 5 9: Qf= 98.65, sd=  1.67, d4=  2.15, Qc= 98.53, s=0.122, Qo= 90.24, P=12, S=900, N=66, Qf1av= 96.20, Qf1max= 97.47
8 3 7 6 12 10 2 4 5 11 9: Qf= 98.65, sd=  1.67, d4=  2.09, Qc= 98.53, s=0.122, Qo= 90.24, P=12, S=900, N=66, Qf1av= 96
```

But if you then recompress and decompress it like this, it fails:

```
$ kanzi -d < kanzi-l4_b32m_error13_no_more_data.log.knz|kanzi -c -t PACK+ROLZ -e NONE -b 32m -j 1|kanzi -d -v 5 -j 1 -o none

Kanzi 2.3.0 (c) Frederic Langlet

Fast lossless data compressor.
Compiled with clang version 16.0 - AVX2
Verbosity: 5
Overwrite: false
Using 1 job
Input file name: 'STDIN'
Output file name: 'none'

Decompressing STDIN ...


{ "type":"DECOMPRESSION_START", "size":0, "time":2150 }
Bitstream version: 6
Block checksum: NONE
Block size: 33554432 bytes
Using no entropy codec (stage 1)
Using PACK+ROLZ transform (stage 2)

{ "type":"BLOCK_INFO", "id":1, "offset":-1, "skipFlags":00111111 }
{ "type":"BEFORE_ENTROPY", "id":1, "size":1698481, "time":2484 }
{ "type":"AFTER_ENTROPY", "id":1, "size":1698477, "time":3616 } [2 ms]
{ "type":"BEFORE_TRANSFORM", "id":1, "size":1698477, "time":3623 }
No more data to read in the bitstream. Error code: 13
```

This was with a binary compiled with clang 16.0.4 but also happens with a gcc 12.2.1 compiled one.  Both produce exactly the same output (same sha256sum) for level 4 (32m) compression of the test data.

The error does not occur with buffer size 8m or 16m.  Also doesn't occur with PACK alone or ROLZ alone.  Or as mentioned with random or pure-zeros input test data.

Tested on: Fedora 36 Linux on AMD Ryzen 9
Built with (for the clang 16.0.4 build, the fastest on this platform among 7 different clang/gcc builds):

`make CXX='clang++ -flto -Rpass=vector' CXXFLAGS='-c -std=c++14 -Wall -Wextra -O3 -fomit-frame-pointer -DNDEBUG -pedantic -march=haswell -fno-rtti' LDFLAGS='-fuse-ld=lld -lpthread' kanzi`

Thanks for your great work, this is a very promising program!

PS: Attachment wrapped in 'gzip -1' because GitHub refuses to accept .knz files.  With only 'gzip -9' instead of kanzi+gzip, the compressed log excerpt would be 2.7 times larger, 1986 KiB instead of 727 KiB!
[kanzi-l4_b32m_error13_no_more_data.log.knz.gz](https://github.com/user-attachments/files/17693160/kanzi-l4_b32m_error13_no_more_data.log.knz.gz)

**Comment by flanglet** [comment] 2024-11-11 01:18
Thank you for the report.
I am able to reproduce the issue. Here are a few quick notes:

```
cat /tmp/1 | ./kanzi -c -t PACK+ROLZ -e NONE -b 32m -j 1 -o /tmp/2 -f
Compressed STDIN: 33554432 => 1698506 (5.06%) in 216 ms
md5sum /tmp/2
9e0a1aadcfec3b994088b11680d4202d  /tmp/2
cat /tmp/2 |  ./kanzi -d -j 1 -o none
No more data to read in the bitstream. Error code: 13

cat /tmp/1 | ./Kanzi -c -t PACK+ROLZ -e NONE -b 32m -j 1 -o /tmp/2 -f
Compressed STDIN: 33554432 => 1698506 (5.06%) in 316 ms
md5sum /tmp/2
9e0a1aadcfec3b994088b11680d4202d  /tmp/2
cat /tmp/2 | ./Kanzi -d -j 1 -o none
Decompressed STDIN: 1698506 => 33554432 in 95 ms
```

The C++ and Go compressors generate the same file. The Go decompressor works, so the bug is in the C++ decompressor. The issue is already present in the 2.3.0 release. I will have to dig.

**Comment by flanglet** [comment] 2024-11-12 20:29
It should be fixed as of commit [15c7b1d](https://github.com/flanglet/kanzi-cpp/commit/15c7b1da3d6c69fde0dc1da5616c8bf19879811b).

**Closed** 2024-11-15 18:00 UTC

**Comment by udickow** [comment] 2024-11-24 16:54
Thanks for the fix.  I can confirm that it solves the problem.  kanzi-cpp can now decompress the entire 5.1 GiB log file after compression with `kanzi -c -l 4 -b 32m` as well as after 37 other more or less interesting combinations of compression levels/algorithms and buffer sizes.

(Due to the log being pre-sorted, it is highly sensitive to block size, with just 8m being optimal for level 9 -- compressed size 153 MiB -- and 128m level 9 blowing up to 402 MiB, much larger than even the 234 MiB for `zstd -19`; best kanzi is 136 MiB for `-t PACK -e TPAQX -b 64m` while `zpaq -m57` (128 MiB buffers better than smaller here) shrinks it to just 118 MiB at the cost of more than 10x the CPU usage of the 136 MiB kanzi).

I should of course have created this issue in the kanzi-cpp project instead of here.  But I realized my mistake too late.

**Comment by flanglet** [comment] 2024-11-24 21:00
Thanks for confirming the fix and providing more details.
It is clear to me that the default levels work well in general but for specific data, nothing can beat dedicated transforms and special combinations of transforms and entropy which is why I build kanzi this way. The best option (depending of the chosen target ratio/speed) in these scenarios is really to try different combinations as you did.
As for zpaq, it is currently too slow for my taste. Maybe in the future, CPUs & memory will be fast enough but I preferred to restrict my PAQ implementation (levels 8 & 9) to something "usable" at the cost of compression ratio.

**Comment by udickow** [comment] 2024-11-24 21:19
Right, I also think zpaq is way too slow.  I'm grateful that you created kanzi as a much more practical alternative for good compression at quite reasonable speed.
