### ISSUE TITLE
"index out of range" error in Go BWT Forward transform

### ISSUE THREAD

**Issue by pzo** [flanglet/kanzi#9] opened 2017-07-23 09:31 UTC
Kanzi --compress --input=bwt2.bin --entropy=none --transform=bwt --force

Kanzi 1.1 (C) 2017,  Frederic Langlet                                                                                                                                                                             
Encoding ...                                                                                                                                                                                                      
panic: runtime error: index out of range                                                                                                                                                                          

goroutine 5 [running]:
kanzi/transform.(*BWT).Forward(0xc42000e900, 0xc4201f2000, 0xcccc, 0xcccc, 0xc420200003, 0xcccd, 0xcccd, 0x3, 0xc420042c80, 0x40cd6d, ...)
        /home/user/go/src/kanzi/transform/BWT.go:146 +0x249
kanzi/function.(*BWTBlockCodec).Forward(0xc42000c0a8, 0xc4201f2000, 0xcccc, 0xcccc, 0xc420200000, 0xccd0, 0xccd0, 0x100, 0x0, 0x101000000000000, ...)
        /home/user/go/src/kanzi/function/BWTBlockCodec.go:73 +0x110
kanzi/function.(*ByteTransformSequence).Forward(0xc42000ad20, 0xc4201f2000, 0xcccc, 0xcccc, 0xc420200000, 0xccd0, 0xccd0, 0x0, 0x0, 0x0, ...)
        /home/user/go/src/kanzi/function/ByteTransformSequence.go:85 +0x1eb
kanzi/io.(*EncodingTask).encode(0xc4200d82a0)
        /home/user/go/src/kanzi/io/CompressedStream.go:466 +0xb97
created by kanzi/io.(*CompressedOutputStream).processBlock
        /home/user/go/src/kanzi/io/CompressedStream.go:391 +0x39d

[bwt2.bin.gz](https://github.com/flanglet/kanzi/files/1167987/bwt2.bin.gz)

**Comment by flanglet** [comment] 2017-07-23 22:36
Interestingly this issue happens in the Java implementation as well but not the C++ one.

**Comment by flanglet** [comment] 2017-07-26 04:01
The root cause is 2 variables initialized in the wrong order in trPartialCopy() in the port of DivSuftSort.

**Comment by flanglet** [comment] 2017-07-27 02:28
This one was hard to locate. Hopefully the last one. Fixed in commit 79b3c36.

**Closed by flanglet** 2017-07-27 02:28 UTC
Labels: bug
